### ISSUE TITLE
vgg16_bn转换时报错

### ISSUE THREAD

**Issue by Jackson8888** [xxradon/PytorchToCaffe#108]
features.0
conv:  blob1
conv1 was added to layers
5128011424:conv_blob1 was added to blobs
add1 was added to layers
5128011640:add_blob1 was added to blobs
WARNING: CANNOT FOUND blob 4533504688
4533504688:extra_blob1 was added to blobs
features.1
batch_norm1 was added to layers
5128011208:batch_norm_blob1 was added to blobs
bn_scale1 was added to layers
features.2
relu1 was added to layers
5072315304:relu_blob1 was added to blobs
features.3
conv:  relu_blob1
conv2 was added to layers
5128010992:conv_blob2 was added to blobs
add2 was added to layers
5128011064:add_blob2 was added to blobs
WARNING: CANNOT FOUND blob 5072316024
Traceback (most recent call last):
  File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/example/vgg19_pytorch_to_caffe.py", line 14, in <module>
    pytorch_to_caffe.trans_net(net, input, name)
  File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/pytorch_to_caffe.py", line 786, in trans_net
    out = net.forward(input_var)
  File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torchvision/models/vgg.py", line 49, in forward
    x = self.features(x)
  File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/Users//.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 113, in forward
    self.num_batches_tracked = self.num_batches_tracked + 1  # type: ignore
  File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/pytorch_to_caffe.py", line 532, in _add
    bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
  File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/Caffe/layer_param.py", line 33, in __init__
    self.bottom.extend(bottom)
TypeError: None has type NoneType, but expected one of: bytes, unicode

**Comment by yanzhou-li** [comment]
> features.0
> conv: blob1
> conv1 was added to layers
> 5128011424:conv_blob1 was added to blobs
> add1 was added to layers
> 5128011640:add_blob1 was added to blobs
> WARNING: CANNOT FOUND blob 4533504688
> 4533504688:extra_blob1 was added to blobs
> features.1
> batch_norm1 was added to layers
> 5128011208:batch_norm_blob1 was added to blobs
> bn_scale1 was added to layers
> features.2
> relu1 was added to layers
> 5072315304:relu_blob1 was added to blobs
> features.3
> conv: relu_blob1
> conv2 was added to layers
> 5128010992:conv_blob2 was added to blobs
> add2 was added to layers
> 5128011064:add_blob2 was added to blobs
> WARNING: CANNOT FOUND blob 5072316024
> Traceback (most recent call last):
> File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/example/vgg19_pytorch_to_caffe.py", line 14, in
> pytorch_to_caffe.trans_net(net, input, name)
> File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/pytorch_to_caffe.py", line 786, in trans_net
> out = net.forward(input_var)
> File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torchvision/models/vgg.py", line 49, in forward
> x = self.features(x)
> File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
> input = module(input)
> File "/Users//.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/Users/.pyenv/versions/env/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 113, in forward
> self.num_batches_tracked = self.num_batches_tracked + 1 # type: ignore
> File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/pytorch_to_caffe.py", line 532, in _add
> bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
> File "/Users/PycharmProjects/paddle_test/PytorchToCaffe/Caffe/layer_param.py", line 33, in **init**
> self.bottom.extend(bottom)
> TypeError: None has type NoneType, but expected one of: bytes, unicode

Hi, I meet the same problem, have you solved it? @Jackson8888
