### ISSUE TITLE
erro when convert mobilenet to caffe

### ISSUE THREAD

**Issue by wytcsuch** [xxradon/PytorchToCaffe#111]
Hello, An error accurs when I run the example mobilenetV2_pytorch_to_caffe.py
```
WARNING: CANNOT FOUND blob 140292285941872
WARNING: CANNOT FOUND blob 140292285942016
cat2 was added to layers
140292285942088:cat_blob2 was added to blobs
features.0.0
WARNING: CANNOT FOUND blob 140292285942304
WARNING: CANNOT FOUND blob 140292285942376
cat3 was added to layers
140292285942016:cat_blob3 was added to blobs
features.0.0
WARNING: CANNOT FOUND blob 140292285942880
WARNING: CANNOT FOUND blob 140292285942736
cat4 was added to layers
140292285943168:cat_blob4 was added to blobs
add1 was added to layers
140292285941224:add_blob1 was added to blobs
WARNING: CANNOT FOUND blob 140292412739448
WARNING: CANNOT FOUND blob 140296772397760
Traceback (most recent call last):
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yckj3822/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/yckj3822/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/yckj3822/.vscode-server/extensions/ms-python.python-2021.5.829140558/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yckj3822/pytorch2caffe/mobilenetV2_pytorch_to_caffe.py", line 37, in <module>
    pytorch_to_caffe.trans_net(net, input, name)
  File "/home/yckj3822/pytorch2caffe/pytorch_to_caffe.py", line 786, in trans_net
    out = net.forward(input_var)
  File "/home/yckj3822/pytorch2caffe/MobileNetV2.py", line 110, in forward
    x = self.features(x)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3822/anaconda3/envs/py35/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py", line 67, in forward
    self.num_batches_tracked += 1
  File "/home/yckj3822/pytorch2caffe/pytorch_to_caffe.py", line 545, in _iadd
    bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
  File "/home/yckj3822/pytorch2caffe/Caffe/layer_param.py", line 33, in __init__
    self.bottom.extend(bottom)
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

torch：1.0.0
torchvision：0.2.0

**Comment by XiaoLaoDi** [comment]
@wytcsuch How did you solved it ?
