### ISSUE TITLE
module 'pytorch2caffe.caffe_pb2' has no attribute 'PermuteParameter'

### ISSUE THREAD

**Issue by xiaonancheng** [xxradon/PytorchToCaffe#120]
I am trying to convert the YOLOv3 pt file to cache and this issue occurred

**Comment by xiaonancheng** [comment]
Traceback (most recent call last):
  File "torch2caff.py", line 102, in <module>
    pytorch2caffe.trans_net(model, dummy_input, name)
  File "/home/nicta100-s26/.local/lib/python3.8/site-packages/pytorch2caffe/pytorch2caffe.py", line 1022, in trans_net
    out = net.forward(input_var)
  File "/home/nicta100-s26/ai/sample/yolov3/hisi_yolo/yolov3-master/models/common.py", line 523, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/nicta100-s26/.conda/envs/torch1x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nicta100-s26/ai/sample/yolov3/hisi_yolo/yolov3-master/models/yolo.py", line 210, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/nicta100-s26/ai/sample/yolov3/hisi_yolo/yolov3-master/models/yolo.py", line 120, in _forward_once
    x = m(x)  # run
  File "/home/nicta100-s26/.conda/envs/torch1x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nicta100-s26/.conda/envs/torch1x/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 153, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
  File "/home/nicta100-s26/.local/lib/python3.8/site-packages/pytorch2caffe/pytorch2caffe.py", line 925, in __call__
    out = self.obj(self.raw, *args, **kwargs)
TypeError: _interpolate() got an unexpected keyword argument 'recompute_scale_factor'
