### ISSUE TITLE
'module' object has no attribute 'walk_stack'

### ISSUE THREAD

**Issue by gailysun** [xxradon/PytorchToCaffe#37]
IHi, thanks for your nice work.
I run the example of resnet_pytorch_2_caffe.py
I downpload the resnet18 from resnet18 : 'https://download.pytorch.org/models/resnet18-5c106cde.pth.
I get the following error. Could you help me find the reason. Thank you very much.
Traceback (most recent call last):
  File "example/resnet_pytorch_2_caffe.py", line 17, in <module>
    pytorch_to_caffe.trans_net(resnet18,input,name)
  File "./pytorch_to_caffe.py", line 613, in trans_net
    out = net.forward(input_var)
  File "/home/scr/anaconda2/envs/pytorchenv/lib/python2.7/site-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/home/scr/anaconda2/envs/pytorchenv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/scr/anaconda2/envs/pytorchenv/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
  File "./pytorch_to_caffe.py", line 528, in __call__
    for stack in traceback.walk_stack(None):
AttributeError: 'module' object has no attribute 'walk_stack'
   
for stack in traceback.walk_stack(None):
AttributeError: 'module' object has no attribute 'walk_stack'

**Comment by xxradon** [comment]
how about update your python to 3.6?
