### ISSUE TITLE
转换vgg11时出错

### ISSUE THREAD

**Issue by slayerlpj** [xxradon/PytorchToCaffe#42]
作者您好，我执行python example/vgg19_pytorch_to_caffe.py转换VGG11到caffe时出错了，请问如何解决？
我的版本是cuda9.0 python3.6 pytorch 1.1.0 caffe-gpu1.0
输出结果如下：

Starting Transform, This will take a while
139790540402336:blob1 was added to blobs
Add blob         blob1         : torch.Size([1, 3, 224, 224])
139790540402336:blob1 getting
torch ops name: {VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (8): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (10): ReLU(inplace)
    (11): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (13): ReLU(inplace)
    (14): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (15): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (16): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (17): ReLU(inplace)
    (18): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (19): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (20): ReLU(inplace)
    (21): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (22): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (23): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (24): ReLU(inplace)
    (25): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (26): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (27): ReLU(inplace)
    (28): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(7, 7))
  (classifier): Sequential(
    (0): Linear(in_features=25088, out_features=4096, bias=True)
    (1): ReLU(inplace)
    (2): Dropout(p=0.5)
    (3): Linear(in_features=4096, out_features=4096, bias=True)
    (4): ReLU(inplace)
    (5): Dropout(p=0.5)
    (6): Linear(in_features=4096, out_features=1000, bias=True)
  )
): '', Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace)
  (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (5): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (6): ReLU(inplace)
  (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (8): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (9): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (10): ReLU(inplace)
  (11): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (12): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (13): ReLU(inplace)
  (14): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (15): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (16): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (17): ReLU(inplace)
  (18): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (19): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (20): ReLU(inplace)
  (21): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (22): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (23): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (24): ReLU(inplace)
  (25): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (26): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (27): ReLU(inplace)
  (28): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
): 'features', Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.0', BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.1', ReLU(inplace): 'features.2', MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 'features.3', Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.4', BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.5', ReLU(inplace): 'features.6', MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 'features.7', Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.8', BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.9', ReLU(inplace): 'features.10', Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.11', BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.12', ReLU(inplace): 'features.13', MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 'features.14', Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.15', BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.16', ReLU(inplace): 'features.17', Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.18', BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.19', ReLU(inplace): 'features.20', MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 'features.21', Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.22', BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.23', ReLU(inplace): 'features.24', Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 'features.25', BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'features.26', ReLU(inplace): 'features.27', MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 'features.28', AdaptiveAvgPool2d(output_size=(7, 7)): 'avgpool', Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace)
  (2): Dropout(p=0.5)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace)
  (5): Dropout(p=0.5)
  (6): Linear(in_features=4096, out_features=1000, bias=True)
): 'classifier', Linear(in_features=25088, out_features=4096, bias=True): 'classifier.0', ReLU(inplace): 'classifier.1', Dropout(p=0.5): 'classifier.2', Linear(in_features=4096, out_features=4096, bias=True): 'classifier.3', ReLU(inplace): 'classifier.4', Dropout(p=0.5): 'classifier.5', Linear(in_features=4096, out_features=1000, bias=True): 'classifier.6'}
features.0
conv1 was added to layers
139790540402264:conv_blob1 was added to blobs
Add blob       conv_blob1      : torch.Size([1, 64, 224, 224])
139790540402336:blob1 getting
139790540402264:conv_blob1 getting
add1 was added to layers
139790540402480:add_blob1 was added to blobs
Add blob       add_blob1       : torch.Size([])
Traceback (most recent call last):
  File "example/vgg19_pytorch_to_caffe.py", line 11, in <module>
    pytorch_to_caffe.trans_net(net,input,name)
  File "./pytorch_to_caffe.py", line 654, in trans_net
    out = net.forward(input_var)
  File "/home/xs/anaconda3/envs/caffe/lib/python3.6/site-packages/torchvision/models/vgg.py", line 42, in forward
    x = self.features(x)
  File "/home/xs/anaconda3/envs/caffe/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xs/anaconda3/envs/caffe/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/xs/anaconda3/envs/caffe/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xs/anaconda3/envs/caffe/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 74, in forward
    self.num_batches_tracked += 1
  File "./pytorch_to_caffe.py", line 496, in _iadd
    bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
  File "./pytorch_to_caffe.py", line 89, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 32, in __getitem__
    return self.data[key]
KeyError: 139791099045136

**Comment by warrentdrew** [comment]
我也有类似的问题，目前的解决方法就是删掉pytorch_to_caffe.py中的
raw__add__=Variable.__add__
Variable.__add__=_add
raw__iadd__=Variable.__iadd__
Variable.__iadd__=_iadd

raw__add__ = t.__add__
t.__add__ = _add
raw__iadd__ = t.__iadd__
t.__iadd__ = _iadd

不知道有没有更好的解决方法
