### ISSUE TITLE
pytorch2caffe error??

### ISSUE THREAD

**Issue by lunalulu** [xxradon/PytorchToCaffe#5]
my env is pytorch 1.0.1.post2
and i want to convert pytorch model to caffe;
1 run python3 example/alexnet_pytorch_to_caffe.py
`140558256725592:view_blob1 was added to blobs
Add blob       view_blob1      : torch.Size([1, 9216])
Traceback (most recent call last):
  File "example/alexnet_pytorch_to_caffe.py", line 12, in <module>
    pytorch_to_caffe.trans_net(net,input,name)
  File "./pytorch_to_caffe.py", line 612, in trans_net
    out = net.forward(input_var)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/alexnet.py", line 46, in forward
    x = x.view(x.size(0), 256 * 6 * 6)
  File "./pytorch_to_caffe.py", line 410, in _view
    bottom=[log.blobs(input)],top=top_blobs)
  File "./pytorch_to_caffe.py", line 88, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 31, in __getitem__
    return self.data[key]
KeyError: 140558256725160
`
2 run python3 example/resnet_pytorch_2_caffe.py
`Traceback (most recent call last):
  File "example/resnet_pytorch_2_caffe.py", line 11, in <module>
    checkpoint = torch.load("/home/luna/mmdnn/imagenet_resnet18.pth")
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1105: ordinal not in range(128)`

**Comment by lunalulu** [comment]
I changed the model of resnet to resnet18-5c106cde.pth，the error below：
`140118547965992:relu_blob17 getting
view1 was added to layers
140118547966064:view_blob1 was added to blobs
Add blob       view_blob1      : torch.Size([1, 512])
Traceback (most recent call last):
  File "example/resnet_pytorch_2_caffe.py", line 17, in <module>
    pytorch_to_caffe.trans_net(resnet18,input,name)
  File "./pytorch_to_caffe.py", line 612, in trans_net
    out = net.forward(input_var)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/resnet.py", line 161, in forward
    x = x.view(x.size(0), -1)
  File "./pytorch_to_caffe.py", line 410, in _view
    bottom=[log.blobs(input)],top=top_blobs)
  File "./pytorch_to_caffe.py", line 88, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 31, in __getitem__
    return self.data[key]
KeyError: 140118547965704
`

**Comment by xxradon** [comment]
I have tested my code in  pytorch 1.0.1.post2 and latest pytorch-nightly,example/alexnet_pytorch_to_caffe.py and example/resnet_pytorch_2_caffe.py are all ok.
And I think you should use anaconda to install pytorch libprotobuf rather than system python3.

**Comment by lunalulu** [comment]
OK，i will try,thanks very much

**Comment by lunalulu** [comment]
hi,i try anaconda install,below is my conda list:
`pytorch                   1.0.1           py3.7_cuda9.0.176_cudnn7.4.2_2    pytorch
libprotobuf               3.7.0                hdbcaa40_0    conda-forge
protobuf                  3.7.0            py37hf484d3e_0    conda-forge
torchvision               0.2.2                      py_3    pytorch
google-auth               1.6.3                      py_0    conda-forge`

but the error still here!

**Comment by lunalulu** [comment]
need install caffe？

**Comment by xxradon** [comment]
@lunalulu caffe is no needed,but protobuf is needed.After install protobuf ,you should read https://github.com/xxradon/PytorchToCaffe/blob/master/Caffe/ReadMe.md to create your caffe_pb2.py by protobuf 3.7.0.

**Comment by lunalulu** [comment]
@xxradon ，it seems the view_blob1 some worry:
`Traceback (most recent call last):
  File "example/resnet_pytorch_2_caffe.py", line 17, in <module>
    pytorch_to_caffe.trans_net(resnet18,input,name)
  File "./pytorch_to_caffe.py", line 612, in trans_net
    out = net.forward(input_var)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/resnet.py", line 161, in forward
    **x = x.view(x.size(0), -1)**
  File "./pytorch_to_caffe.py", line 410, in _view
    bottom=[log.blobs(input)],top=top_blobs)
  File "./pytorch_to_caffe.py", line 88, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 31, in __getitem__
    return self.data[key]`

**Comment by xxradon** [comment]
I am sorry , I never met such error when I run the example.

**Comment by lunalulu** [comment]
@xxradon Can you help me turn the following model:
checkpoint_resnet18.pth   this saving format is below:

> torch.save({'epoch': epoch,
                    'step': step,
                    'net_state_dict': net.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict()},
                   cfg.CHECKPOINT_PATH)

resnet18_full.pth is Entire Model, its saving format is torch.save(model, path)
download from 
链接：https://pan.baidu.com/s/1BV2i4F7A_pi2mg3-CXw5fQ 
提取码：qulk

**Comment by xxradon** [comment]
Resnet18 model code is needed,can you paste to here?

**Comment by lunalulu** [comment]
@xxradon yes, the link contains two versions of the file. '.pth'

**Comment by lunalulu** [comment]
@xxradon note that, the resnet18 model is modified, and implemented on the pytorch version 0.4.1

**Comment by xxradon** [comment]
@lunalulu I mean,where is your resnet18 training code,or inference code？I cannot test with just one model   file.

**Comment by lunalulu** [comment]
@xxradon ，sorry，this project：
https://github.com/wangziren1/pytorch_pose_proposal_networks

**Comment by strawberryfg** [comment]
@lunalulu Hi lunalulu, I worked it out. It turns out that the current version lacks of the transformation of "AdaptiveAvgPool2d" which is needed in https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py. And so the **_view** cannot find **log.blobs(input)** since the global average pooling has not been registered yet.


See the code below for details. It should work.
`
#Mar 26, 2019
def _adaptive_avg_pool2d(raw, input, output_size):
    _output_size = _list_with_default(output_size, input.size())
    x = raw(input, _output_size)

    #for debug
    #print("adaptive now")
    #print(_output_size)
    #print(id(input))
    #print(input.shape)
    #input.shape[2] should equal input.shape[3]
    _pool('ave', raw, input, x, input.shape[2], input.shape[2], 0, False)
    return x
`

`
#Added Mar 26, 2019
F.adaptive_avg_pool2d=Rp(F.adaptive_avg_pool2d, _adaptive_avg_pool2d)
`

Don't forget to include
`from torch.nn.modules.utils import _list_with_default
`

For reference, the adaptive function is borrowed from PyTorch implementation https://pytorch.org/docs/stable/_modules/torch/nn/functional.html.

I am not sure if PyTorch 0.3, 0.4 or whatever < 1.0 can work nicely.

**Comment by smocilac** [comment]
@strawberryfg
Can you give me a more detailed description on how to solve this issue? I have a very similar traceback: 

`conv1 was added to layers
140445320738784:conv_blob1 was added to blobs
Add blob       conv_blob1      : torch.Size([1, 64, 512, 1024])
Traceback (most recent call last):
  File "swiftnet_to_caffe.py", line 25, in <module>
    pytorch_to_caffe.trans_net(model, input_, name)
  File "./pytorch_to_caffe.py", line 630, in trans_net
    out = net.do_forward(data)
  File "./models/semseg.py", line 36, in do_forward
    return self.forward(**data)
  File "./models/semseg.py", line 16, in forward
    feats, additional = zip(*[self.backbone(p) for p in pyramid])
  File "./models/semseg.py", line 16, in <listcomp>
    feats, additional = zip(*[self.backbone(p) for p in pyramid])
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "./models/resnet/resnet_single_scale.py", line 221, in forward
    return self.forward_up(self.forward_down(image))
  File "./models/resnet/resnet_single_scale.py", line 193, in forward_down
    x = self.conv1(image)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
  File "./pytorch_to_caffe.py", line 535, in __call__
    out=self.obj(self.raw,*args,**kwargs)
  File "./pytorch_to_caffe.py", line 104, in _conv2d
    bottom=[log.blobs(input)], top=[log.blobs(x)])
  File "./pytorch_to_caffe.py", line 89, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 32, in __getitem__
    return self.data[key]
KeyError: 140445320738352`

**Comment by strawberryfg** [comment]
@smocilac 
Hi, I remember this keyerror is caused by missing bottom blob. That is to say, the bottom blob image is missing. What does you resnet_single_scale.py look like? I guess conv1(image) is the first layer? 

Looking at the first line of _conv2d, I think either the "input" is not defined or the hyper-parameter e.g. bias is not interpreted. What I would do is to print everything I can come up with up to "layer=caffe_net.Layer.param(balabala), since this line triggers the exception.

**Comment by strawberryfg** [comment]
BTW, does you single scale mean 64x64? AFAK the prototxt generated will output
layer {
  name: "max_pool1"
  type: "Pooling"
  bottom: "relu_blob1"
  top: "max_pool_blob1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 1
  }
}
for ResNet 50

I commented the line "pad: 1" cause I found that the feature downsampled is not 7x7 for 224x224 input . After removing this layer I can load pretrained weights from others. 

I think F.conv2d is not reading "pad: 1". You might want to hack this line. And I trained the model for a while to reach similar performance as pytorch counterpart.

**Comment by smocilac** [comment]
@strawberryfg
Thank you, all I had to do is to downsample/prepare image properly.

**Comment by strawberryfg** [comment]
You can try 252x252 or something like that. Well it's a bit sketchy... These deep learning frameworks have a lot of subtle differences.

**Comment by lstomy** [comment]
Hi, I am trying to convert own mobilenet model but faced with an issue like guys abowe "KeyError: 140445320738352".

So, I decided to examine example/mobilenetV2_pytorch_to_caffe.py more carefully. I run it and it was succeeded (caffe models were generated). But if I add print(input_var) in the pytorch_to_caffe.py at line right after NET_INITTED=True (line 608), it fails with a log:

Starting Transform, This will take a while
140498049307056:blob1 was added to blobs
Add blob         blob1         : torch.Size([1, 3, 224, 224])
140498049307056:blob1 getting
view1 was added to layers
140498049306696:view_blob1 was added to blobs
Add blob       view_blob1      : torch.Size([150528])
Traceback (most recent call last):
  File "example/mobilenetV2_pytorch_to_caffe.py", line 21, in <module>
    pytorch_to_caffe.trans_net(net, input, name)
  File "./pytorch_to_caffe.py", line 637, in trans_net
    print(input_var)
  File "/virtualenvs/python35/lib/python3.5/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/virtualenvs/python35/lib/python3.5/site-packages/torch/_tensor_str.py", line 256, in _str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/virtualenvs/python35/lib/python3.5/site-packages/torch/_tensor_str.py", line 82, in __init__
    copy = torch.empty(tensor.size(), dtype=torch.float64).copy_(tensor).view(tensor.nelement())
  File "./pytorch_to_caffe.py", line 419, in _view
    bottom=[log.blobs(input)],top=top_blobs)
  File "./pytorch_to_caffe.py", line 90, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 31, in __getitem__
    return self.data[key]
KeyError: 140498049306984

Could you, please, help to understand why it has such behavior? It is just printing of the torch.Tensor. Can it be connected with redefinition of the Variable.view() function at the line 403, def _view(input, *args)? If does, how exactly it is related to redefinition of the Variable.view() function?

Many thanks for any suggestions.

**Comment by AshishSardana** [comment]
@lstomy @strawberryfg Hi there,
I'm getting the KeyError for all the models - alexnet, inceptionnet, mobilenetV2.
My environment has pytorch==0.4, caffe==1.0, protobuf==3.7.0

Can you guide me on how you were able to move past this error?
Thanks, Ashish
![image](https://user-images.githubusercontent.com/22201681/58169812-4d544480-7caf-11e9-95f4-e5c8181faaea.png)

**Comment by JayLSU** [comment]
@AshishSardana, according to @strawberryfg's comments, you could first include 
`from torch.nn.modules.utils import _list_with_default`
and then add  

```
def _adaptive_avg_pool2d(raw, input, output_size): 

    _output_size = _list_with_default(output_size, input.size())

    x = raw(input, _output_size)

    _pool('ave', raw, input, x, input.shape[2], input.shape[2], 0, False)

    return x 
```
and 
` F.adaptive_avg_pool2d=Rp(F.adaptive_avg_pool2d, _adaptive_avg_pool2d) `
in pytorch_to_caffe.py. At least, according to my experience, it solves the alexnet problem.

**Comment by JayLSU** [comment]
@strawberryfg  HI, I am trying to convert shufflenetv2 from pythorch to caffemodel, when I am doing the conversion, I found some strange result. From the output, I noticed that the batch norm layers and relu layers are overwritten each other 
```
conv1.2
{140534397259992: 'blob1', 140534397338320: 'conv_blob1', 140534397338536: 'batch_norm_blob1'}
140534397338536:batch_norm_blob1 getting
{140534397259992: 'blob1', 140534397338320: 'conv_blob1', 140534397338536: 'batch_norm_blob1'}
relu1 was added to layers
140534397338536:relu_blob1 was added to blobs
Add blob       relu_blob1      : torch.Size([1, 24, 112, 112])
{140534397259992: 'blob1', 140534397338320: 'conv_blob1', 140534397338536: 'relu_blob1'}
140534397338536:relu_blob1 getting
{140534397259992: 'blob1', 140534397338320: 'conv_blob1', 140534397338536: 'relu_blob1'}
maxpool
max_pool1 was added to layers
...
```
You can see that the blob id are the same for batch_norm_blob1 and relu_blob1 and then  relu_blob1 will overwrite that blob.  Another is also the KeyError problem caused by bottom image missing. 
```
Traceback (most recent call last):
  File "example/shufflenetv2_pytorch_to_caffe.py", line 15, in <module>
    pytorch_to_caffe.trans_net(net,input,name)
  File "./pytorch_to_caffe.py", line 631, in trans_net
    out = net.forward(input_var)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/shufflenetv2.py", line 125, in forward
    x = self.stage2(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/shufflenetv2.py", line 78, in forward
    out = channel_shuffle(out, 2)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/shufflenetv2.py", line 30, in channel_shuffle
    x = x.view(batchsize, -1, height, width)
  File "./pytorch_to_caffe.py", line 428, in _view
    bottom=[log.blobs(input)],top=top_blobs)
  File "./pytorch_to_caffe.py", line 90, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 33, in __getitem__
    return self.data[key]
KeyError: 140534397340192
```
However, I thought it might be caused by channel_shuffle() layer but I have not fixed it yet. 
The shufflenetv2.py is from [here](https://github.com/pytorch/vision/blob/master/torchvision/models/shufflenetv2.py) and I use shufflenet_v2_x1_0 in my script. Could provide any suggestion? Thanks in advance. 
Jay

**Comment by strawberryfg** [comment]
HI @JayLSU . I think the issue may be caused by line 27 since the error message points to line 30(#flatten). I haven't used .contiguous and I have no idea what that means. Maybe you can print x within the function "channel_shuffle"?

**Comment by strawberryfg** [comment]
Does the "overwriting" lead to any error? The batch norm blob "blob1" will be forwarded to relu blob to generate another "blob1". They are the same in terms of "top". If it does not result in any error, I believe the generated prototxt will be correct. I might have missed anything?

**Comment by trohit920** [comment]
@strawberryfg @xxradon @lunalulu Hello, i am trying to convert Hopenet ( Head Pose Estimation model) from pytorch to caffe using this repository. But i am getting an error. Please take a look: 
```
`Traceback (most recent call last):
  File "alexnet_pytorch_to_caffe.py", line 23, in <module>
    pytorch_to_caffe.trans_net(model,input,name)
  File "./pytorch_to_caffe.py", line 621, in trans_net
    out = net.forward(input_var)
  File "./hopenet.py", line 57, in forward
    x = self.bn1(x)
  File "/home/rohit/.virtualenvs/Pytorch2Caffe/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rohit/.virtualenvs/Pytorch2Caffe/lib/python3.5/site-packages/torch/nn/modules/batchnorm.py", line 74, in forward
    self.num_batches_tracked += 1
  File "./pytorch_to_caffe.py", line 465, in _iadd
    bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
  File "./pytorch_to_caffe.py", line 89, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 32, in __getitem__
    return self.data[key]
KeyError: 140582292714984
```
Any advice will really be helpful. Thanks in advance.

**Comment by trohit920** [comment]
Here is how the Hopenet model is defined.

```
import torch
import torch.nn as nn
from torch.autograd import Variable
import math
import torch.nn.functional as F

class Hopenet(nn.Module):
    # Hopenet with 3 output layers for yaw, pitch and roll
    # Predicts Euler angles by binning and regression with the expected value
    def __init__(self, block, layers, num_bins):
        self.inplanes = 64
        super(Hopenet, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)
        self.avgpool = nn.AvgPool2d(7)
        self.fc_yaw = nn.Linear(512 * block.expansion, num_bins)
        self.fc_pitch = nn.Linear(512 * block.expansion, num_bins)
        self.fc_roll = nn.Linear(512 * block.expansion, num_bins)

        # Vestigial layer from previous experiments
        self.fc_finetune = nn.Linear(512 * block.expansion + 3, 3)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        pre_yaw = self.fc_yaw(x)
        pre_pitch = self.fc_pitch(x)
        pre_roll = self.fc_roll(x)

        return pre_yaw, pre_pitch, pre_roll

class ResNet(nn.Module):
    # ResNet for regression of 3 Euler angles.
    def __init__(self, block, layers, num_classes=1000):
        self.inplanes = 64
        super(ResNet, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2)
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2)
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2)
        self.avgpool = nn.AvgPool2d(7)
        self.fc_angles = nn.Linear(512 * block.expansion, num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()

    def _make_layer(self, block, planes, blocks, stride=1):
        downsample = None
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                nn.Conv2d(self.inplanes, planes * block.expansion,
                          kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample))
        self.inplanes = planes * block.expansion
        for i in range(1, blocks):
            layers.append(block(self.inplanes, planes))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc_angles(x)
        return x

class AlexNet(nn.Module):
    # AlexNet laid out as a Hopenet - classify Euler angles in bins and
    # regress the expected value.
    def __init__(self, num_bins):
        super(AlexNet, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(64, 192, kernel_size=5, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(192, 384, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(384, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
        )
        self.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
        )
        self.fc_yaw = nn.Linear(4096, num_bins)
        self.fc_pitch = nn.Linear(4096, num_bins)
        self.fc_roll = nn.Linear(4096, num_bins)

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), 256 * 6 * 6)
        x = self.classifier(x)
        yaw = self.fc_yaw(x)
        pitch = self.fc_pitch(x)
        roll = self.fc_roll(x)
        return yaw, pitch, roll
```
Model is using Resnet as bottleneck. Any help will be hugely appreciated.

**Comment by jixiaonanzhuaizhuai** [comment]
@JayLSU HI, I am also trying to convert shufflenetv2 from pythorch to caffemodel. Do you have fixed it about the keyerror of channel_shuffle() layer caused. I have the same problem. can you give me some ideas?

**Comment by jixiaonanzhuaizhuai** [comment]
@lunalulu @strawberryfg  Hi, I am trying to convert shufflenetv2 from pythorch to caffemodel. I have the same keyError. Any help will be hugely appreciated. I thought it might be caused by channel_shuffle() layer  x = x.view(batchsize, -1, height, width) .

def channel_shuffle(x, groups):
    batchsize, num_channels, height, width = x.data.size()
    channels_per_group = num_channels // groups
    #reshape
    x = x.view(batchsize, groups, channels_per_group, height, width)
    #transpose
    x = torch.transpose(x, 1, 2).contiguous()
    #flatten
    x = x.view(batchsize, -1, height, width)
    return x

####error information
------------pytorch_to_caffe.py-----------------------------input: torch.Size([1, 24, 2, 48, 80])
------------pytorch_to_caffe.py-----------------------------x: torch.Size([1, 48, 48, 80])
view2 was added to layers
139668331934488:view_blob2 was added to blobs
Add blob       view_blob2      : torch.Size([1, 48, 48, 80])
Traceback (most recent call last):
  File "msra_pytorch_to_caffe.py", line 46, in <module>
    pytorch_to_caffe.trans_net(net, input, name)
  File "../pytorch_to_caffe.py", line 628, in trans_net
    out = net.forward(input_var)
  File "/home/yanan/zongmu/PytorchToCaffe/example/v16_d4_msra_resnet.py", line 336, in forward
    x = channel_shuffle(x, 2)
  File "/home/yanan/zongmu/PytorchToCaffe/example/v16_d4_msra_resnet.py", line 49, in channel_shuffle
    x = x.view(batchsize, -1, height, width)
  File "../pytorch_to_caffe.py", line 418, in _view
    print("------------pytorch_to_caffe.py-----------------------------log.blobs(input):", log.blobs(input))
  File "../pytorch_to_caffe.py", line 89, in blobs
    print("------------pytorch_to_caffe.py-----------------------------var:", self._blobs[var])
  File "../pytorch_to_caffe.py", line 33, in __getitem__
    return self.data[key]
KeyError: 139668331925080

**Comment by chaipangpang** [comment]
@JayLSU Thanks，this method can also solve the problem of other networks.

**Comment by chaipangpang** [comment]
@strawberryfg Thanks, this works.

**Comment by OPPOA113** [comment]
@jixiaonanzhuaizhuai pytorch转caffe时，view算子的能解析吗。这个问题解决了吗？我也遇到view转caffe时出错的问题。。。
有没有人遇到过view转caffe时出现问题的，怎么解决的？求支招，感谢！！！

**Comment by gmt710** [comment]
@jixiaonanzhuaizhuai hello, Have you solved this problem?

**Comment by April4lu** [comment]
> @jixiaonanzhuaizhuai pytorch转caffe时，view算子的能解析吗。这个问题解决了吗？我也遇到view转caffe时出错的问题。。。
> 有没有人遇到过view转caffe时出现问题的，怎么解决的？求支招，感谢！！！

view算子的问题在模型转换中得到解决了么？
