### ISSUE TITLE
讀不到 batchnrom

### ISSUE THREAD

**Issue by twmht** [xxradon/PytorchToCaffe#8]
我轉 resnet 是正常的，但轉這個範例就不行...

```
import torch
import torch.nn as nn

class Conv_block(torch.nn.Module):
    def __init__(self, in_c, out_c, kernel=(1, 1), stride=(1, 1), padding=(0, 0), groups=1):
        super(Conv_block, self).__init__()
        self.conv_kk = torch.nn.Conv2d(in_c, out_channels=out_c, kernel_size=kernel, groups=groups, stride=stride, padding=padding, bias=False)
        self.bn_kk = nn.BatchNorm2d(out_c)
        #  self.prelu = torch.nn.PReLU(out_c)
    def forward(self, x):
        x = self.conv_kk(x)
        x = self.bn_kk(x)
        #  x = self.prelu(x)
        return x

class MobileFaceNet(torch.nn.Module):
    def __init__(self, embedding_size, net_type='GNAP'):
        super(MobileFaceNet, self).__init__()

        self.base_modules = nn.Sequential(Conv_block(3, 64, kernel=(3, 3), stride=(2, 2), padding=(1, 1)))

    def forward(self, x):

        x = self.base_modules(x)

        return x
```

貌似在這邊沒辦法抓到

```
    def __call__(self,*args,**kwargs):
        if not NET_INITTED:
            return self.raw(*args,**kwargs)
        for stack in traceback.walk_stack(None):
            if 'self' in stack[0].f_locals:
                layer=stack[0].f_locals['self']
                if layer in layer_names:
                    log.pytorch_layer_name=layer_names[layer]
                    print('layer {}'.format(log.pytorch_layer_name)) # 這邊不會印 bn
                    break
        out=self.obj(self.raw,*args,**kwargs)
        # if isinstance(out,Variable):
        #     out=[out]
        return out

```

traceback

```
Traceback (most recent call last):
  File "example/mobilenet_pytorch_to_caffe.py", line 14, in <module>
    pytorch_to_caffe.trans_net(net, inp, name)
  File "./pytorch_to_caffe.py", line 616, in trans_net
    out = net.forward(input_var)
  File "./model/mobilenet.py", line 38, in forward
    x = self.base_modules(x)
  File "/home/tumh/.pyenv/versions/pytorch-python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tumh/.pyenv/versions/pytorch-python3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/tumh/.pyenv/versions/pytorch-python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "./model/mobilenet.py", line 21, in forward
    x = self.bn_kk(x)
  File "/home/tumh/.pyenv/versions/pytorch-python3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tumh/.pyenv/versions/pytorch-python3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 67, in forward
    self.num_batches_tracked += 1
  File "./pytorch_to_caffe.py", line 459, in _iadd
    bottom=[log.blobs(input),log.blobs(args[0])], top=top_blobs)
  File "./pytorch_to_caffe.py", line 89, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "./pytorch_to_caffe.py", line 32, in __getitem__
    return self.data[key]
KeyError: 139891738811560
```

是需要什麼特別的寫法才能過？

**Comment by twmht** [comment]
少了 net.eval()

**Comment by ltcs11** [comment]
VGG19 同理
